services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    # command: ['./bin/rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    command: ['./bin/rails', 'server', '-p', '4000']

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      # - RAILS_ENV=development

    ports:
      - 4000:4000

    stdin_open: true

    tty: true

    volumes:
      - .:/home/darnoc/app
      - shared-data:/var/shared
      - gem-cache:/usr/local/bundle/gems

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.5-bullseye

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - shared-data:/var/shared

    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    ports:
      - 5433:5432

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: {}
  gem-cache: {}
  shared-data: {}
